# Generated by Django 4.1.5 on 2023-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_likemodel_friendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
